### ISSUE TITLE
Build ready For FiveM

### ISSUE THREAD

**Issue by Yozzagg** [Jesper-Hustad/NoPixel-minigame#10]
Working on converting this for you.

**Comment by Jesper-Hustad** [comment]
Thanks for the support.
So if I get this right you want a special version of the repo that can be run on FiveM the GTA V multiplayer mod system.

I unfortunately have no experience working with FiveM, i only made this because i enjoyed the NoPixel version.

FiveM can run html natively, I'm unsure how you make it ineract with the rest of the game, global variables and functions?

For me it would be an honor to have the mini game implemented in other servers for people to enjoy.

If you can help me in any way with getting started, a template or just some requirements to make it work i can give it a shot.

**Comment by Jesper-Hustad** [comment]
Don't know much about FiveM, asking the community for help here.
Please comment if you can, anything helps!

- What are special considerations and hurdles associated with creating for FiveM?
- How does the data flow between FiveM code and HTML?
- How do you package a release, how is it shared?

**Comment by OverloadFran** [comment]
Hey, i builded for FiveM, add me on discord and i will send to you the package to update the repo. Ty for share ur work! 
Discord: miau#6690

**Comment by OverloadFran** [comment]
> Don't know much about FiveM, asking the community for help here.
> Please comment if you can, anything helps!
> 
> * What are special considerations and hurdles associated with creating for FiveM?
> * How does the data flow between FiveM code and HTML?
> * How do you package a release, how is it shared?

Hey, i builded for FiveM, add me on discord and i will send to you the package to update the repo. Ty for share ur work!
Discord: miau#6690

**Comment by imtorchedbud** [comment]
> > Don't know much about FiveM, asking the community for help here.
> > Please comment if you can, anything helps!
> > 
> > * What are special considerations and hurdles associated with creating for FiveM?
> > * How does the data flow between FiveM code and HTML?
> > * How do you package a release, how is it shared?
> 
> Hey, i builded for FiveM, add me on discord and i will send to you the package to update the repo. Ty for share ur work!
> Discord: miau#6690
hey i messaged you on discord i wanna test this

**Comment by Pavan576** [comment]
can you check your email @Jesper-Hustad

**Comment by LumpyAU** [comment]
Hi did you end up getting this to work for fiveM

**Comment by imtorchedbud** [comment]
Hey no I’m still coding it out for qbus it’s taking a bit because I need to build the NUI base and make callbacks for them I’ll keep up as much as I can

**Comment by Jesper-Hustad** [comment]
Ok i pulled a FiveM version.
There is a readme you can read about it [here](https://github.com/Jesper-Hustad/NoPixel-minigame/tree/main/fivem-script).
Feel free to give feedback on this, if it's working for guys i will close this issue as we have accomplished our mission!
