### ISSUE TITLE
[Puzzle / FiveM]: returning part of answer as undefined

### ISSUE THREAD

**Issue by GeerdoDaGr8** [Jesper-Hustad/NoPixel-minigame#33]
Certain ones are getting returned back undefined.  The one i got a couple times with the number collor and the correct answer was yellow but it came back as undefined
![image](https://user-images.githubusercontent.com/56656726/128973234-10c5cb2a-007a-4cab-af26-b43f1b22aa47.png)

**Comment by GeerdoDaGr8** [comment]
Seems to be and issue with the answer of yellow

**Comment by Jesper-Hustad** [comment]
So this happened because i added translation because someone requested it (so it's easier for spanish/italiens etc. to use), but i screwed up and misspelled one variable `numer`. So i changed the variable back to `number` now.

![image](https://user-images.githubusercontent.com/17168694/129010789-1d6df472-a178-44ca-b3f9-45a0750a8439.png)

Side note this same issue was recently fixed except it was the website version, so it seems the FiveM version had the exact same issue. https://github.com/Jesper-Hustad/NoPixel-minigame/pull/32

Thanks for mentioning the issue, it's very helpfull!

**Comment by yamiM0NSTER** [comment]
Oh, fivem script duplicates website code? Thought there would be some script to copy if that was the case. My bad.

**Comment by Jesper-Hustad** [comment]
> Oh, fivem script duplicates website code? Thought there would be some script to copy if that was the case. My bad.

You are right, that's how it's supposed to be (i believe because of the way FiveM works you could even have it running directly from the site code), but alas that's not the way it is.

When a project starts as a one off thing and suddenly you are getting new issues weekly and maintaining code that's not really designed for scalibility 😅
