### ISSUE TITLE
[Puzzle / FiveM]: Language change 

### ISSUE THREAD

**Issue by doctorassi** [Jesper-Hustad/NoPixel-minigame#48]
We can only change the color names.

**Comment by Jesper-Hustad** [comment]
I added the language feature because someone said they couldn't remember the colors.

I agree having full language support with feature a button or something would be helpful.

I don't have a lot of time to maintain this, so if you want to add this feel free!

It would be quite some work translating all text programatically, there are standards and tutorials for how this is done you could probably look up.

**Comment by Jesper-Hustad** [comment]
Languages are now fully supported
