### ISSUE TITLE
Colors seem to not be rendering properly as of recent.

### ISSUE THREAD

**Issue by cshess** [Jesper-Hustad/NoPixel-minigame#53]
Hi, the minigame was fine yesterday, but since the latest push, some colors are rendering as pitch black.
I've tried it on firefox and opera, but the issue persists.
Example photo:
![image](https://user-images.githubusercontent.com/39418524/159380564-f34c52ee-3db1-468b-b443-fe20c2a8cc97.png)

**Comment by Creeamy** [comment]
I think thats because the border color he uses is black so it blends in with the shapes or background if the color behind it is black too. A solution could be to just make it so black can only appear once one square. Or that the border is white/black depending on the background behind it. I don't know how to configure that though.

**Comment by Jesper-Hustad** [comment]
There is code that is supposed to check for this, so yes something has gone wrongs.

Thank you so much for reporting the issue will take a look as soon as possible.

**Comment by Jesper-Hustad** [comment]
Missed one hashtag that made red display as black.
Fixed now.
Once again, thanks for reporting!
