### ISSUE TITLE
Questions tend to be mostly about color when clicking refresh button

### ISSUE THREAD

**Issue by bobsantos** [Jesper-Hustad/NoPixel-minigame#9]
Browser: Chrome

Whenever time expires and no answers are entered, clicking refresh tends to give you questions based on color. Going to the address bar and hitting enter seems to fix this.

**Comment by Jesper-Hustad** [comment]
5/6 questions include something about color.  You get two questions each round.
If you try refreshing three times you should expect to only be getting color questions 33% of the time.

Would be difficult to test if this really is a bug, or just expected behaviour statistically.
Maybe i have misunderstood, what do you think?
